#!/usr/bin/env ruby

$LOAD_PATH.unshift "#{Dir.getwd}/lib"

#require 'shellopts'

require 'forward_to'
include ForwardTo

require 'constrain'
include Constrain

require './lib/shellopts/ext/array.rb'
require './lib/shellopts/token.rb'
require './lib/shellopts/lexer.rb'
require './lib/shellopts/line.rb'

#include ShellOpts::Message
#include ShellOpts::Verbose
#include ShellOpts::Debug

#include ShellOpts::Messages
#p ShellOpts::Messages.is_included?

SPEC = %(
  Some text

  Some
  multiline
  text

  -a @brief description
    An option

  command! -- CMDARG1 CMDARG2 @brief description of command
    A command

    -c
      @brief description of the command option
      An option for the command

  -- ARG

  another_command!
    -d
      @ option -d brief
      Option -d description
    -- ARGS HERE
    @ brief here
    Description here
)

lexer = ShellOpts::Lexer.new("main", SPEC, false)

pp lexer.lex

exit


opts, args = ShellOpts.process(SPEC, ARGV, version: "--ver", version_number: "1.2.3", help: "-?,help")

verb "Verbose default"
(0..3).each { |i| verb i, "Verbose #{i}" }
mesg "Message"
notice "Notice"
#debug "Debug"


