#!/usr/bin/bash

rspec --fail-fast \
    spec/ext/{follow,stringio,tree}_spec.rb \
    spec/{line,type,lexer,parser,analyzer,args}_spec.rb \
    spec/grammar_spec.rb \
    spec/shellopts/shellopts_spec.rb

